name: jcli
version: git
summary: Jenkins CLI allows you manage your Jenkins in an easy way.
description: |
  Jenkins CLI allows you manage your Jenkins in an easy way. No matter if you're a plugin developer, administrator or just a regular user, it is made for you!

confinement: devmode
base: core18
license: MIT
grade: devel

parts:
  jcli:
    plugin: go
    go-importpath: github.com/jenkins-zh/jenkins-cli
    source: .
    source-type: git
    build-pakcages:
      - gcc
apps:
  jcli:
    command: jcli
