name: Build Snapcraft

on:
  push:
    branches:
    - master

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1.1.3
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
          use_lxd: true

      - name: Build Snapcraft
        run: sg lxd -c 'snapcraft --use-lxd'
